


const numero = 0
if( numero > 0){
  console.log("Positivo")
}else if( numero < 0){
  console.log("Negativo")
}else{
  console.log("zero")
}


const number = 0



const idade = 18
if (idade > 18 && idade < 65){
  console.log("Ela e Obrigagatoria a votar")
}else if( idade == 16){
  console.log("Ela pode Votar")
}else if (idade >1 || idade < 15){
  console.log("Ela e menor de idade e nao pode")
}

